tail_prompts: [
  '',
  '\nここまでの議論で合意できたポイントを整理した上で意見を述べてください',
  '\nここまでの議論と異なる意見を述べてください',
  '\n今まで出た意見を整理した上で深掘りする意見を出してください',
  '\nこれまでの意見の中で一番有効と思う発言を元に深掘りする意見を出してください',
  '\n意見の違いがあるようですが、共通点は何かを踏まえて具体案を出してください',
  '\n他の視点から考えるとどうかを踏まえて具体案を出してください'
]
state_names: ['発散', '収束', '平行線', 'その他']
state_judge_prompt: |-
  以下の発言からなる議論は次の選択肢のうち、どの状態ですか？簡潔に答えてください。
  議論内容:
  ${__comments__}

  選択肢:
  ${__options__}
legal_prompts_dict: {
  '発散': [0, 1, 2, 3, 4, 5, 6],
  '収束': [0, 1, 2, 3, 4, 5, 6],
  '平行線': [0, 1, 2, 3, 4, 5, 6],
  'その他': [0, 1, 2, 3, 4, 5, 6]
}
embedding_model_name: llm-book/bert-base-japanese-v3-unsup-simcse-jawiki
torch_device: cpu